apiVersion: v1
kind: Secret
metadata:
  name: bugzilla-secrets
  namespace: bugzilla
  labels:
    app.kubernetes.io/name: bugzilla
    app.kubernetes.io/component: web
type: Opaque
stringData:
  BUGZILLA_ADMIN_PASSWORD: "change-me"
  BUGZILLA_DB_PASS: "change-me"
