apiVersion: v1
kind: ServiceAccount
metadata:
  name: bugzilla
  namespace: bugzilla
  labels:
    app.kubernetes.io/name: bugzilla
    app.kubernetes.io/part-of: bugzilla-platform
automountServiceAccountToken: false
