ServerTokens Prod
ServerSignature Off
TraceEnable Off

<VirtualHost *:8080>
    ServerName localhost
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html/bugzilla
    DirectoryIndex index.cgi index.html

    ErrorLog ${APACHE_LOG_DIR}/bugzilla-error.log
    CustomLog ${APACHE_LOG_DIR}/bugzilla-access.log "%h %l %u %t \"%m %U\" %>s %O"

    <Directory /var/www/html/bugzilla>
        AllowOverride All
        Options +ExecCGI +FollowSymLinks -Indexes
        AddHandler cgi-script .cgi
        Require all granted
    </Directory>

    <Directory /var/www/html/bugzilla/data>
        Require all denied
    </Directory>

    <Directory /var/www/html/bugzilla/docs>
        Options -ExecCGI
    </Directory>
</VirtualHost>
