{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "bugzilla.fullname" . }}
  namespace: {{ include "bugzilla.namespace" . }}
  labels:
    {{- include "bugzilla.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  podSelector:
    matchLabels:
      {{- include "bugzilla.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- if .Values.networkPolicy.ingressNamespacesAny }}
        - namespaceSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
  egress:
    {{- if .Values.networkPolicy.egressAllowDns }}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        {{- range .Values.networkPolicy.egressAdditionalPorts }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
{{- end }}
