{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bugzilla.secretName" . }}
  namespace: {{ include "bugzilla.namespace" . }}
  labels:
    {{- include "bugzilla.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
type: Opaque
stringData:
  BUGZILLA_ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  BUGZILLA_DB_PASS: {{ .Values.secrets.dbPassword | quote }}
{{- end }}
